SELECT CASE WHEN A.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL
            THEN 0
            ELSE 1
       END AS TP_ETAPA
     , 'Solicitado' AS DS_ETAPA
     , C.DT_HISTORICO_SCOMPRA AS DATA
     , H.NOME
     , H.NOME_COMPLETO
     , CAST('' AS VARCHAR(1000)) AS JUSTIFICATIVA
     , CASE WHEN A.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL
            THEN 0
            ELSE D.NR_PROCESSO_COMPRA
       END AS NR_DOCUMENTO
     , CASE WHEN A.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL
            THEN 0
            ELSE D.ANO_PROCESSO_COMPRA
       END AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_HISTORICO_SCOMPRA   C ON C.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       LEFT  JOIN AAC_USUARIOS            H ON H.CODIGO_USUARIO         = A.ID_SOLICITANTE
       LEFT  JOIN SUP_PROCESSO_COMPRA     D ON D.ID_PROCESSO_COMPRA     = A.ID_PROCESSO_COMPRA
 WHERE B.ID_COMPRA_ITEM        = :ID_COMPRA_ITEM
   AND C.ST_SOLICITACAO_COMPRA = :ST_SOLICITACAO_COMPRA_ABERTO

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Liberado' AS DS_ETAPA
     , C.DT_HISTORICO_SCOMPRA AS DATA
     , H.NOME
     , H.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_HISTORICO_SCOMPRA   C ON C.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       LEFT  JOIN AAC_USUARIOS            H ON H.CODIGO_USUARIO         = A.ID_SOLICITANTE
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_SOLICITACAO_COMPRA = :ST_SOLICITACAO_COMPRA_LIBERADO

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Aprovado' AS DS_ETAPA
     , C.DT_HISTORICO_SCOMPRA AS DATA
     , H.NOME
     , H.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_HISTORICO_SCOMPRA   C ON C.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       LEFT  JOIN AAC_USUARIOS            H ON H.CODIGO_USUARIO         = A.ID_APROVADOR
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_SOLICITACAO_COMPRA = :ST_SOLICITACAO_COMPRA_APROVADO

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Reprovado' AS DS_ETAPA
     , C.DT_HISTORICO_SCOMPRA AS DATA
     , H.NOME
     , H.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_HISTORICO_SCOMPRA   C ON C.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       LEFT  JOIN AAC_USUARIOS            H ON H.CODIGO_USUARIO         = A.ID_APROVADOR
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_SOLICITACAO_COMPRA = :ST_SOLICITACAO_COMPRA_REPROVADO

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Aprovação financeira - aprovado' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_COMPRA_ITEM = :ST_COMPRA_ITEM_LIBERADO_DOT
  AND 1 = :UTILIZA_APROV_FIN

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Aprovação financeira - reprovado' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , C.JUSTIFICATIVA AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_COMPRA_ITEM = :ST_COMPRA_ITEM_NAO_LIBERADO_DOT
   AND 1 = :UTILIZA_APROV_FIN

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Definição de dotação - liberado' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND CASE WHEN (0 = :UTILIZA_DEF_COMPRADOR OR A.TP_SOLICITACAO <> :TP_SOLICITACAO_NORMAL)
            THEN CAST(:ST_COMPRA_ITEM_LIBERADO_COMPRA AS INTEGER)
            ELSE CAST(:ST_COMPRA_ITEM_LIB_LIBERACAO AS INTEGER)
       END = C.ST_COMPRA_ITEM

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Definição de dotação - não liberado' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , C.JUSTIFICATIVA AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND CASE WHEN (0 = :UTILIZA_DEF_COMPRADOR OR A.TP_SOLICITACAO <> :TP_SOLICITACAO_NORMAL)
            THEN CAST(:ST_COMPRA_ITEM_NAO_LIBERADO_COMPRA AS INTEGER)
            ELSE CAST(:ST_COMPRA_ITEM_NAO_LIB_LIBERACAO AS INTEGER)
       END = C.ST_COMPRA_ITEM

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Autorização de compra - liberado' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_COMPRA_ITEM = :ST_COMPRA_ITEM_LIBERADO_COMPRA
   AND 1 = :UTILIZA_DEF_COMPRADOR
   AND A.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Autorização de compra - não liberado' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , C.JUSTIFICATIVA AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_COMPRA_ITEM = :ST_COMPRA_ITEM_NAO_LIBERADO_COMPRA
   AND 1 = :UTILIZA_DEF_COMPRADOR
   AND A.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Definição de comprador - definido' AS DS_ETAPA
     , H.DT_COMPRA_ITEM_ID AS DATA
     , I.NOME
     , I.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_COMPRA_ITEM_ID      H ON H.ID_COMPRA_ITEM_ID      = B.ID_COMPRA_ITEM_ID
       LEFT  JOIN AAC_USUARIOS            I ON I.CODIGO_USUARIO         = H.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Definição de comprador - não definido' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , C.JUSTIFICATIVA AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_COMPRA_ITEM = :ST_COMPRA_ITEM_RECUSADO_DEF_COMP

UNION ALL

SELECT 1 AS TP_ETAPA
     , 'Em processo de compra' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , F.NR_PROCESSO_COMPRA AS NR_DOCUMENTO
     , F.ANO_PROCESSO_COMPRA AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
       LEFT  JOIN SUP_PROC_COMPRA_ITEM    E ON E.ID_PROC_COMPRA_ITEM    = B.ID_PROC_COMPRA_ITEM
       LEFT  JOIN SUP_PROCESSO_COMPRA     F ON F.ID_PROCESSO_COMPRA     = E.ID_PROCESSO_COMPRA
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND A.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL
   AND C.ST_COMPRA_ITEM = :ST_COMPRA_ITEM_EM_PROCESSO

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Recusado pelo comprador' AS DS_ETAPA
     , C.DT_HISTORICO_COMPRA_IT AS DATA
     , D.NOME AS NOME
     , D.NOME_COMPLETO AS NOME_COMPLETO
     , C.JUSTIFICATIVA AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , B.QTD
     , B.VL_TOTAL
  FROM SUP_COMPRA_ITEM B
       INNER JOIN SUP_SOLICITACAO_COMPRA  A ON A.ID_SOLICITACAO_COMPRA  = B.ID_SOLICITACAO_COMPRA
       INNER JOIN SUP_HISTORICO_COMPRA_IT C ON C.ID_COMPRA_ITEM         = B.ID_COMPRA_ITEM
       LEFT  JOIN AAC_USUARIOS            D ON D.CODIGO_USUARIO         = C.ID_USUARIO
 WHERE B.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND C.ST_COMPRA_ITEM = :ST_COMPRA_ITEM_RECUSADO

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Ratificado/adjudicado' AS DS_ETAPA
     , CASE WHEN H.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL
            THEN C.DT_RATIFICACAO
            ELSE E.DT_RATIFICACAO
       END AS DATA
     , CASE WHEN H.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL
            THEN D.NOME
            ELSE F.NOME
       END AS NOME
     , CASE WHEN H.TP_SOLICITACAO = :TP_SOLICITACAO_NORMAL
            THEN D.NOME_COMPLETO
            ELSE F.NOME_COMPLETO
       END AS NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , G.QTD
     , G.VL_TOTAL
  FROM SUP_RATIF_FICHA_DADOS A
       LEFT JOIN SUP_RATIF_FICHA        B ON B.ID_RATIF_FICHA_DADOS   = A.ID_RATIF_FICHA_DADOS
       LEFT JOIN SUP_RATIF_ITEM_HIST    C ON C.ID_RATIF_ITEM          = B.ID_RATIF_ITEM
                                         AND C.ID_RATIF_ITEM_HIST     = (SELECT FIRST 1 A3.ID_RATIF_ITEM_HIST
                                                                           FROM SUP_RATIF_ITEM_HIST A3
                                                                          WHERE A3.ID_RATIF_ITEM = B.ID_RATIF_ITEM )
       LEFT JOIN AAC_USUARIOS           D ON D.CODIGO_USUARIO         = C.ID_USUARIO
       LEFT JOIN SUP_RATIF_FICHA_HIST   E ON E.ID_RATIF_FICHA         = B.ID_RATIF_FICHA AND E.ID_RATIF_FICHA_DADOS = B.ID_RATIF_FICHA_DADOS
                                         AND E.ID_RATIF_FICHA_HIST    = (SELECT FIRST 1 A4.ID_RATIF_FICHA_HIST
                                                                           FROM SUP_RATIF_FICHA_HIST A4
                                                                          WHERE A4.ID_RATIF_FICHA = B.ID_RATIF_FICHA
                                                                            AND A4.ID_RATIF_FICHA_DADOS = B.ID_RATIF_FICHA_DADOS )
       LEFT JOIN AAC_USUARIOS           F ON F.CODIGO_USUARIO         = E.ID_USUARIO
       LEFT JOIN SUP_COMPRA_ITEM        G ON G.ID_COMPRA_ITEM         = A.ID_COMPRA_ITEM
       LEFT JOIN SUP_SOLICITACAO_COMPRA H ON H.ID_SOLICITACAO_COMPRA  = G.ID_SOLICITACAO_COMPRA
 WHERE A.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND H.TP_SOLICITACAO IN (:TP_SOLICITACAO_NORMAL, :TP_SOLICITACAO_ADITAMENTO)
 GROUP BY
       A.ID_COMPRA_ITEM,
       H.TP_SOLICITACAO,
       C.DT_RATIFICACAO,
       E.DT_RATIFICACAO,
       D.NOME,
       F.NOME,
       D.NOME_COMPLETO,
       F.NOME_COMPLETO,
       C.VL_TOTAL,
       G.QTD,
       G.VL_TOTAL

UNION ALL

SELECT 0 AS TP_ETAPA
     , 'Anulado' AS DS_ETAPA
     , B.DT_ANULACAO AS DATA
     , C.NOME
     , C.NOME_COMPLETO
     , B.JUSTIFICATIVA_ANULACAO AS JUSTIFICATIVA
     , 0 AS NR_DOCUMENTO
     , 0 AS ANO_DOCUMENTO
     , A.QTD
     , A.VL_TOTAL
  FROM SUP_COMPRA_ITEM A
       INNER JOIN SUP_PROC_COMPRA_ITEM  B ON B.ID_PROC_COMPRA_ITEM  = A.ID_PROC_COMPRA_ITEM
       LEFT  JOIN AAC_USUARIOS          C ON C.CODIGO_USUARIO       = B.ID_USUARIO_ANULACAO
 WHERE A.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND B.ANULADO = 1

UNION ALL

SELECT 2 AS TP_ETAPA
     , 'Solicitação de empenho - solicitado' AS DS_ETAPA
     , E.DT_SOLICITACAO AS DATA
     , F.NOME
     , F.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , E.NR_SOLIC_EMPENHO AS NR_DOCUMENTO
     , E.CP_ANO AS ANO_DOCUMENTO
     , SUM(C.QTD) AS QTD
     , SUM(C.VALOR) AS VALOR
  FROM SUP_RATIF_FICHA_DADOS A
       INNER JOIN SUP_RATIF_FICHA         B ON B.ID_RATIF_FICHA_DADOS   = A.ID_RATIF_FICHA_DADOS
       INNER JOIN SUP_SOLIC_EMPENHO_FICHA C ON C.ID_RATIF_FICHA         = B.ID_RATIF_FICHA
       INNER JOIN SUP_SOLIC_EMPENHO_ITEM  D ON D.ID_SOLIC_EMPENHO_ITEM  = C.ID_SOLIC_EMPENHO_ITEM
       INNER JOIN SUP_SOLIC_EMPENHO       E ON E.ID_SOLIC_EMPENHO       = D.ID_SOLIC_EMPENHO
       LEFT  JOIN AAC_USUARIOS            F ON F.CODIGO_USUARIO         = E.ID_SOLICITANTE
 WHERE A.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND E.ID_ST_SOLIC_EMPENHO <> :ST_PEDIDO_COMPOSICAO_CANCELADO
 GROUP BY
       E.DT_SOLICITACAO,
       F.NOME,
       F.NOME_COMPLETO,
       E.NR_SOLIC_EMPENHO,
       E.CP_ANO

UNION ALL

SELECT 2 AS TP_ETAPA
     , 'Solicitação de empenho - liberado' AS DS_ETAPA
     , E.DT_LIBERACAO AS DATA
     , F.NOME
     , F.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , E.NR_SOLIC_EMPENHO AS NR_DOCUMENTO
     , E.CP_ANO AS ANO_DOCUMENTO
     , SUM(C.QTD) AS QTD
     , SUM(C.VALOR) AS VALOR
  FROM SUP_RATIF_FICHA_DADOS A
       INNER JOIN SUP_RATIF_FICHA         B ON B.ID_RATIF_FICHA_DADOS   = A.ID_RATIF_FICHA_DADOS
       INNER JOIN SUP_SOLIC_EMPENHO_FICHA C ON C.ID_RATIF_FICHA         = B.ID_RATIF_FICHA
       INNER JOIN SUP_SOLIC_EMPENHO_ITEM  D ON D.ID_SOLIC_EMPENHO_ITEM  = C.ID_SOLIC_EMPENHO_ITEM
       INNER JOIN SUP_SOLIC_EMPENHO       E ON E.ID_SOLIC_EMPENHO       = D.ID_SOLIC_EMPENHO
       LEFT  JOIN AAC_USUARIOS            F ON F.CODIGO_USUARIO         = E.ID_USUARIO_LIBERACAO
 WHERE A.ID_COMPRA_ITEM       = :ID_COMPRA_ITEM
   AND E.ID_ST_SOLIC_EMPENHO <> :ST_PEDIDO_COMPOSICAO_CANCELADO
   AND E.DT_LIBERACAO IS NOT NULL
 GROUP BY
       E.DT_LIBERACAO,
       F.NOME,
       F.NOME_COMPLETO,
       E.NR_SOLIC_EMPENHO,
       E.CP_ANO

UNION ALL

SELECT 2 AS TP_ETAPA
     , 'Solicitação de empenho - empenhado' AS DS_ETAPA
     , G.DT_HR_EXECUCAO AS DATA
     , F.NOME
     , F.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , E.NR_SOLIC_EMPENHO AS NR_DOCUMENTO
     , E.CP_ANO AS ANO_DOCUMENTO
     , SUM(C.QTD) AS QTD
     , SUM(C.VALOR) AS VALOR
  FROM SUP_RATIF_FICHA_DADOS A
       INNER JOIN SUP_RATIF_FICHA         B ON B.ID_RATIF_FICHA_DADOS   = A.ID_RATIF_FICHA_DADOS
       INNER JOIN SUP_SOLIC_EMPENHO_FICHA C ON C.ID_RATIF_FICHA         = B.ID_RATIF_FICHA
       INNER JOIN SUP_SOLIC_EMPENHO_ITEM  D ON D.ID_SOLIC_EMPENHO_ITEM  = C.ID_SOLIC_EMPENHO_ITEM
       INNER JOIN SUP_SOLIC_EMPENHO       E ON E.ID_SOLIC_EMPENHO       = D.ID_SOLIC_EMPENHO
       INNER JOIN API_PEDIDO_EXECUCAO     G ON G.ID_PEDIDO_COMPOSICAO   = E.ID_PEDIDO_COMPOSICAO
       LEFT  JOIN AAC_USUARIOS            F ON F.CODIGO_USUARIO         = G.ID_USUARIO_EXECUCAO
 WHERE A.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND G.DT_HR_EXECUCAO IS NOT NULL
 GROUP BY
       G.DT_HR_EXECUCAO,
       F.NOME,
       F.NOME_COMPLETO,
       E.NR_SOLIC_EMPENHO,
       E.CP_ANO

UNION ALL

SELECT 3 AS TP_ETAPA
     , 'Solicitação de estorno - estornado' AS DS_ETAPA
     , G.DT_HR_EXECUCAO AS DATA
     , F.NOME
     , F.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , E.NR_SOLIC_ESTORNO AS NR_DOCUMENTO
     , E.CP_ANO AS ANO_DOCUMENTO
     , SUM(C.QTD) AS QTD
     , SUM(C.VALOR) AS VALOR
  FROM SUP_RATIF_FICHA_DADOS A
       INNER JOIN SUP_RATIF_FICHA         B ON B.ID_RATIF_FICHA_DADOS   = A.ID_RATIF_FICHA_DADOS
       INNER JOIN SUP_SOLIC_EMPENHO_FICHA C ON C.ID_RATIF_FICHA         = B.ID_RATIF_FICHA
       INNER JOIN SUP_SOLIC_EMPENHO_ITEM  D ON D.ID_SOLIC_EMPENHO_ITEM  = C.ID_SOLIC_EMPENHO_ITEM
       INNER JOIN SUP_SOLIC_ESTORNO       E ON E.ID_SOLIC_ESTORNO       = D.ID_SOLIC_ESTORNO
       INNER JOIN API_PEDIDO_EXECUCAO     G ON G.ID_PEDIDO_COMPOSICAO   = E.ID_PEDIDO_COMPOSICAO
       LEFT  JOIN AAC_USUARIOS            F ON F.CODIGO_USUARIO         = G.ID_USUARIO_EXECUCAO
 WHERE A.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND G.DT_HR_EXECUCAO IS NOT NULL
 GROUP BY
       G.DT_HR_EXECUCAO,
       F.NOME,
       F.NOME_COMPLETO,
       E.NR_SOLIC_ESTORNO,
       E.CP_ANO

UNION ALL

SELECT 4 AS TP_ETAPA
     , 'Autorização de fornecimento' AS DS_ETAPA
     , E.DT_CADASTRO AS DATA
     , F.NOME
     , F.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , E.NR_AUTORIZACAO AS NR_DOCUMENTO
     , E.ANO_AUTORIZACAO AS ANO_DOCUMENTO
     , SUM(D.QTD) AS QTD
     , SUM(D.VALOR) AS VALOR
  FROM SUP_RATIF_FICHA_DADOS A
       INNER JOIN SUP_RATIF_FICHA         B ON B.ID_RATIF_FICHA_DADOS   = A.ID_RATIF_FICHA_DADOS
       INNER JOIN SUP_SOLIC_EMPENHO_FICHA C ON C.ID_RATIF_FICHA         = B.ID_RATIF_FICHA
       INNER JOIN SUP_AUTORIZACAO_FICHA   D ON D.ID_SOLIC_EMPENHO_FICHA = C.ID_SOLIC_EMPENHO_FICHA
       INNER JOIN SUP_AUTORIZACAO         E ON E.ID_AUTORIZACAO         = D.ID_AUTORIZACAO
       LEFT  JOIN AAC_USUARIOS            F ON F.CODIGO_USUARIO         = E.ID_RESPONSAVEL
 WHERE A.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
   AND E.ID_ST_AUTORIZACAO <> :ST_AUTORIZACAO_CANCELADO
 GROUP BY
       E.DT_CADASTRO,
       F.NOME,
       F.NOME_COMPLETO,
       E.NR_AUTORIZACAO,
       E.ANO_AUTORIZACAO

UNION ALL

SELECT 5 AS TP_ETAPA
     , 'Liberação de NF' AS DS_ETAPA
     , G.DT_CADASTRO AS DATA
     , F.NOME
     , F.NOME_COMPLETO
     , '' AS JUSTIFICATIVA
     , G.ID_LIBERACAO_NF AS NR_DOCUMENTO
     , UDF_YEAR(G.DT_LIBERACAO_NF) AS ANO_DOCUMENTO
     , SUM(E.QTD) AS QTD
     , SUM(E.VALOR) AS VALOR
  FROM SUP_RATIF_FICHA_DADOS A
       INNER JOIN SUP_RATIF_FICHA         B ON B.ID_RATIF_FICHA_DADOS   = A.ID_RATIF_FICHA_DADOS
       INNER JOIN SUP_SOLIC_EMPENHO_FICHA C ON C.ID_RATIF_FICHA         = B.ID_RATIF_FICHA
       INNER JOIN SUP_AUTORIZACAO_FICHA   D ON D.ID_SOLIC_EMPENHO_FICHA = C.ID_SOLIC_EMPENHO_FICHA
       INNER JOIN SUP_LIBERACAO_NF_FICHA  E ON E.ID_AUTORIZACAO_FICHA   = D.ID_AUTORIZACAO_FICHA
       INNER JOIN SUP_LIBERACAO_NF        G ON G.ID_LIBERACAO_NF        = E.ID_LIBERACAO_NF
       LEFT  JOIN AAC_USUARIOS            F ON F.CODIGO_USUARIO         = G.ID_USUARIO
 WHERE A.ID_COMPRA_ITEM = :ID_COMPRA_ITEM
 GROUP BY
       G.DT_CADASTRO,
       F.NOME,
       F.NOME_COMPLETO,
       G.ID_LIBERACAO_NF,
       G.DT_LIBERACAO_NF